/// A single surgical replacement of a byte range in the original source.
///
/// `start == end` is an insertion. Everything the transpiler does is expressed as
/// a list of these; unchanged source is never touched.
#[derive(Clone, Debug)]
pub struct Edit {
    pub start: usize,
    pub end: usize,
    /// Raw replacement bytes (PHP source isn't guaranteed UTF-8, and a captured
    /// name spliced into `use (...)` may itself contain non-UTF-8 bytes).
    pub replacement: Vec<u8>,
}

impl Edit {
    pub fn replace(start: usize, end: usize, replacement: impl Into<Vec<u8>>) -> Self {
        Edit {
            start,
            end,
            replacement: replacement.into(),
        }
    }

    pub fn insert(at: usize, text: impl Into<Vec<u8>>) -> Self {
        Edit {
            start: at,
            end: at,
            replacement: text.into(),
        }
    }
}

/// How a run of generated bytes relates to the original source.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SegmentKind {
    /// Copied verbatim: generated bytes correspond 1:1 to the source range
    /// (equal length), so positions map exactly.
    Verbatim,
    /// Produced by an edit's replacement text. The source range is what it
    /// replaced; positions inside anchor to `src_start` (the construct's start).
    Synthesized,
}

/// A contiguous mapping between a generated byte range and a source byte range.
/// Segments are emitted in output order and tile `[0, generated.len())` with no
/// gaps, which is what makes them a complete, binary-searchable source map.
#[derive(Clone, Copy, Debug)]
pub struct Segment {
    pub out_start: usize,
    pub out_end: usize,
    pub src_start: usize,
    pub src_end: usize,
    pub kind: SegmentKind,
}

/// Apply edits to the source by splicing, returning the generated text *and* the
/// segment map describing where every generated byte came from.
///
/// Unchanged regions are copied verbatim, so formatting, comments, and — with
/// line-preserving desugarings — line numbers of untouched code are preserved
/// exactly. The segment map is a byproduct of the same walk: provenance is
/// intrinsic to span-splicing, so no separate pass (or output AST) is needed.
///
/// Edits must not overlap. Ties at the same start are ordered insertions-first
/// (end ascending) so an inserted `use (...)` lands before an adjacent replace.
pub fn apply(src: &[u8], mut edits: Vec<Edit>) -> (Vec<u8>, Vec<Segment>) {
    edits.sort_by_key(|e| (e.start, e.end));

    let mut out = Vec::with_capacity(src.len() + 64);
    let mut segments = Vec::new();
    let mut cursor = 0; // position in source
    let mut out_pos = 0; // position in generated output

    let push_verbatim = |out: &mut Vec<u8>, segments: &mut Vec<Segment>, out_pos: &mut usize, from: usize, to: usize| {
        if to > from {
            let len = to - from;
            segments.push(Segment {
                out_start: *out_pos,
                out_end: *out_pos + len,
                src_start: from,
                src_end: to,
                kind: SegmentKind::Verbatim,
            });
            out.extend_from_slice(&src[from..to]);
            *out_pos += len;
        }
    };

    for edit in edits {
        assert!(
            edit.start >= cursor,
            "overlapping edits at {}..{} (cursor {})",
            edit.start,
            edit.end,
            cursor
        );
        push_verbatim(&mut out, &mut segments, &mut out_pos, cursor, edit.start);

        let rlen = edit.replacement.len();
        if rlen > 0 {
            segments.push(Segment {
                out_start: out_pos,
                out_end: out_pos + rlen,
                src_start: edit.start,
                src_end: edit.end,
                kind: SegmentKind::Synthesized,
            });
            out.extend_from_slice(&edit.replacement);
            out_pos += rlen;
        }
        cursor = edit.end;
    }
    push_verbatim(&mut out, &mut segments, &mut out_pos, cursor, src.len());

    (out, segments)
}
