//! Source maps: translate positions in generated PHP back to pxp source.
//!
//! The primary consumer is our own tooling (exception/stack-trace translation),
//! and PHP stack traces are line-granular, so the serialized map is line-based.
//! We deliberately do *not* use Source Map v3 / VLQ for v1 — it's column-oriented
//! and built for JS, and we're our own consumer. The on-disk form is a compact
//! list of `(generated_line -> source_line)` anchors; lines between anchors
//! advance 1:1. A line-preserving transpile collapses to a single `(1, 1)` anchor
//! (the identity map), which also lets tests *assert* line-preservation.
//!
//! The internal derivation works from [`Segment`]s in byte coordinates, so it
//! stays general enough to emit a richer (column-level, v3) format later.

use crate::emit::{Segment, SegmentKind};
use crate::line_index::LineIndex;

pub struct SourceMap {
    pub source_path: String,
    pub generated_path: String,
    /// Sorted by generated line. Both fields 1-based.
    anchors: Vec<(u32, u32)>,
    generated_lines: u32,
}

impl SourceMap {
    /// Derive a line map from the segment map produced by [`crate::emit::apply`].
    pub fn from_segments(
        source_path: impl Into<String>,
        generated_path: impl Into<String>,
        source: &[u8],
        generated: &[u8],
        segments: &[Segment],
    ) -> SourceMap {
        let src_idx = LineIndex::new(source);
        let gen_idx = LineIndex::new(generated);
        let generated_lines = gen_idx.line_count() as u32;

        let mut anchors: Vec<(u32, u32)> = Vec::new();
        let (mut prev_gen, mut prev_src) = (0u32, 0u32);
        for gen_line in 1..=generated_lines {
            let gen_byte = gen_idx.line_start(gen_line);
            let src_byte = source_byte_of(segments, gen_byte, generated.len());
            let src_line = src_idx.line_of(src_byte);

            // Emit an anchor only where the mapping stops advancing 1:1.
            let expected = if anchors.is_empty() {
                u32::MAX
            } else {
                prev_src + (gen_line - prev_gen)
            };
            if src_line != expected {
                anchors.push((gen_line, src_line));
            }
            prev_gen = gen_line;
            prev_src = src_line;
        }

        SourceMap {
            source_path: source_path.into(),
            generated_path: generated_path.into(),
            anchors,
            generated_lines,
        }
    }

    /// Translate a 1-based generated line to its source line.
    pub fn source_line(&self, generated_line: u32) -> u32 {
        let idx = self.anchors.partition_point(|a| a.0 <= generated_line);
        if idx == 0 {
            return generated_line; // no anchors: identity fallback
        }
        let (anchor_gen, anchor_src) = self.anchors[idx - 1];
        anchor_src + (generated_line - anchor_gen)
    }

    /// True when every generated line maps to the same source line — i.e. the
    /// transpile was fully line-preserving.
    pub fn is_identity(&self) -> bool {
        self.anchors.as_slice() == [(1, 1)]
    }

    /// Serialize to the compact `PXPMAP1` text format.
    pub fn serialize(&self) -> String {
        let mut s = String::new();
        s.push_str("PXPMAP1\n");
        s.push_str(&self.source_path);
        s.push('\n');
        s.push_str(&self.generated_path);
        s.push('\n');
        s.push_str(&self.generated_lines.to_string());
        s.push('\n');
        for (gen, src) in &self.anchors {
            s.push_str(&format!("{gen}\t{src}\n"));
        }
        s
    }

    /// Parse the `PXPMAP1` text format. Returns `None` on a malformed header.
    pub fn parse(text: &str) -> Option<SourceMap> {
        let mut lines = text.lines();
        if lines.next()? != "PXPMAP1" {
            return None;
        }
        let source_path = lines.next()?.to_string();
        let generated_path = lines.next()?.to_string();
        let generated_lines = lines.next()?.parse().ok()?;
        let mut anchors = Vec::new();
        for line in lines {
            let (gen, src) = line.split_once('\t')?;
            anchors.push((gen.parse().ok()?, src.parse().ok()?));
        }
        Some(SourceMap {
            source_path,
            generated_path,
            anchors,
            generated_lines,
        })
    }
}

/// Map a generated byte offset back to a source byte offset via the segment map.
fn source_byte_of(segments: &[Segment], gen_byte: usize, gen_len: usize) -> usize {
    let Some(last) = segments.last() else {
        return 0;
    };
    // At/past EOF (e.g. the start of a trailing empty line): anchor to the end of
    // source so it resolves to the final source line, not the previous one.
    if gen_byte >= gen_len {
        return last.src_end;
    }
    let idx = segments.partition_point(|s| s.out_start <= gen_byte);
    let seg = &segments[idx.saturating_sub(1)];
    match seg.kind {
        SegmentKind::Verbatim => seg.src_start + (gen_byte - seg.out_start),
        SegmentKind::Synthesized => seg.src_start,
    }
}

#[cfg(test)]
mod tests {
    use super::SourceMap;
    use crate::emit::{self, Edit};

    fn map_of(src: &str, edits: Vec<Edit>) -> SourceMap {
        let (generated, segments) = emit::apply(src.as_bytes(), edits);
        SourceMap::from_segments("in.pxp", "out.php", src.as_bytes(), &generated, &segments)
    }

    #[test]
    fn line_preserving_transpile_is_identity() {
        // The real short-closure feature is line-preserving, so its map must be
        // the identity — this is a machine-checkable form of that guarantee.
        let src = b"<?php\n$f = fn ($x) => {\n    return $x * $factor;\n};\n";
        let (generated, segments) = emit::apply(src, crate::transform::run_all(src));
        let map = SourceMap::from_segments("in.pxp", "out.php", src, &generated, &segments);
        assert!(map.is_identity(), "map: {}", map.serialize());
        assert!(String::from_utf8_lossy(&generated).contains("use ($factor)"));
    }

    #[test]
    fn plain_php_maps_1_to_1() {
        let map = map_of("<?php\nA\nB\nC\n", vec![]);
        assert!(map.is_identity());
        for line in 1..=4 {
            assert_eq!(map.source_line(line), line);
        }
    }

    #[test]
    fn multi_line_replacement_shifts_following_lines() {
        // Replace the single line "B" (source line 3) with three lines.
        let src = "<?php\nA\nB\nC\n";
        let b_start = src.find('B').unwrap();
        let map = map_of(src, vec![Edit::replace(b_start, b_start + 1, "X\nY\nZ".as_bytes())]);

        assert!(!map.is_identity());
        assert_eq!(map.source_line(1), 1); // <?php
        assert_eq!(map.source_line(2), 2); // A
        // The three synthesized lines all anchor to B's source line (3).
        assert_eq!(map.source_line(3), 3);
        assert_eq!(map.source_line(4), 3);
        assert_eq!(map.source_line(5), 3);
        // C shifted down by two, but resolves back to its true source line (4).
        assert_eq!(map.source_line(6), 4);
    }

    #[test]
    fn round_trips_through_serialization() {
        let src = "<?php\nA\nB\nC\n";
        let b_start = src.find('B').unwrap();
        let map = map_of(src, vec![Edit::replace(b_start, b_start + 1, "X\nY\nZ".as_bytes())]);

        let reparsed = SourceMap::parse(&map.serialize()).unwrap();
        assert_eq!(reparsed.source_path, "in.pxp");
        for line in 1..=6 {
            assert_eq!(reparsed.source_line(line), map.source_line(line));
        }
    }
}
